"""
Builds IOC files from enriched.csv:
  ioc/domains_high.txt         — HIGH severity domains
  ioc/domains_all_malicious.txt — HIGH + MEDIUM domains
  ioc/indicators.csv           — SIEM-ready full indicators
  data/high_severity.csv       — HIGH subset
  data/dead_domains.csv        — DEAD/PARKING/ERROR subset

Usage:
    python scan/build_ioc.py
"""

import csv
from pathlib import Path

ENRICHED = Path("data/enriched.csv")
IOC_DIR  = Path("ioc")
DATA_DIR = Path("data")
csv.field_size_limit(10_000_000)

INDICATOR_COLS = [
    "domain", "ip", "ip_country", "server", "server_fp",
    "favicon_mmh3", "category", "severity", "severity_label",
    "brand", "threat_sources", "registered_at", "expiring_at",
]


def main():
    with open(ENRICHED, newline="", encoding="utf-8-sig", errors="replace") as f:
        rows = list(csv.DictReader(f))
    print(f"[*] {len(rows)} rows loaded")

    IOC_DIR.mkdir(exist_ok=True)

    high   = [r for r in rows if r.get("severity_label") == "HIGH" or
              int(r.get("severity") or 0) >= 3]
    medium = [r for r in rows if r.get("severity_label") == "MEDIUM" or
              int(r.get("severity") or 0) == 2]
    dead   = [r for r in rows if r.get("category") in ("DEAD","PARKING","ERROR") or
              r.get("page_type") in ("DEAD","TIMEOUT","ERROR")]

    # domain blocklists
    with open(IOC_DIR / "domains_high.txt", "w", encoding="utf-8") as f:
        f.write("# NICENIC (IANA #3765) — HIGH severity domains\n")
        f.write(f"# Generated by PhishDestroy — June 2026\n")
        f.write(f"# {len(high)} entries\n\n")
        for r in sorted(high, key=lambda x: x.get("domain","")):
            f.write(r["domain"] + "\n")

    all_mal = high + medium
    with open(IOC_DIR / "domains_all_malicious.txt", "w", encoding="utf-8") as f:
        f.write("# NICENIC (IANA #3765) — HIGH + MEDIUM severity domains\n")
        f.write(f"# Generated by PhishDestroy — June 2026\n")
        f.write(f"# {len(all_mal)} entries\n\n")
        for r in sorted(all_mal, key=lambda x: x.get("domain","")):
            f.write(r["domain"] + "\n")

    # SIEM indicators CSV
    with open(IOC_DIR / "indicators.csv", "w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=INDICATOR_COLS, extrasaction="ignore")
        writer.writeheader()
        for r in sorted(all_mal, key=lambda x: -int(x.get("severity") or 0)):
            writer.writerow({k: r.get(k,"") for k in INDICATOR_COLS})

    # HIGH subset CSV
    fieldnames = list(rows[0].keys())
    with open(DATA_DIR / "high_severity.csv", "w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(sorted(high, key=lambda x: -int(x.get("severity") or 0)))

    # DEAD subset CSV
    with open(DATA_DIR / "dead_domains.csv", "w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(dead)

    print(f"[+] HIGH: {len(high)}  MEDIUM: {len(medium)}  DEAD: {len(dead)}")
    print(f"    ioc/domains_high.txt       — {len(high)} domains")
    print(f"    ioc/domains_all_malicious.txt — {len(all_mal)} domains")
    print(f"    ioc/indicators.csv         — {len(all_mal)} indicators")
    print(f"    data/high_severity.csv     — {len(high)} rows")
    print(f"    data/dead_domains.csv      — {len(dead)} rows")


if __name__ == "__main__":
    main()
